// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID         int32
	Title      string
	Year       int32
	Tagline    string
	Genres     string
	Budget     string
	Director   string
	Actor1     string
	Actor2     string
	Popularity float64
	PosterUrl  sql.NullString
}

type MovieOfTheDay struct {
	Date    time.Time
	MovieID int32
}
