// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Movie struct {
	ID                  int32
	Title               string
	Year                sql.NullInt32
	Tagline             sql.NullString
	Genres              sql.NullString
	Budget              sql.NullInt64
	Director            sql.NullString
	Actor1              sql.NullString
	Actor2              sql.NullString
	Popularity          sql.NullFloat64
	PosterUrl           sql.NullString
	OriginalTitle       sql.NullString
	OriginalLanguage    sql.NullString
	Overview            sql.NullString
	Status              sql.NullString
	Homepage            sql.NullString
	ImdbID              sql.NullString
	ReleaseDate         sql.NullTime
	Runtime             sql.NullInt32
	Revenue             sql.NullInt64
	VoteAverage         sql.NullFloat64
	VoteCount           sql.NullInt32
	Adult               sql.NullBool
	Video               sql.NullBool
	PosterPath          sql.NullString
	BackdropPath        sql.NullString
	BelongsToCollection pqtype.NullRawMessage
	ProductionCompanies pqtype.NullRawMessage
	ProductionCountries pqtype.NullRawMessage
	SpokenLanguages     pqtype.NullRawMessage
	OriginCountry       pqtype.NullRawMessage
	CreditsCast         pqtype.NullRawMessage
	CreditsCrew         pqtype.NullRawMessage
}

type MovieOfTheDay struct {
	Date    time.Time
	MovieID int32
}
