// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID         int32
	Title      string
	Year       sql.NullInt32
	Tagline    sql.NullString
	Genres     sql.NullString
	Budget     sql.NullString
	Director   sql.NullString
	Actor1     sql.NullString
	Actor2     sql.NullString
	Popularity sql.NullFloat64
	PosterUrl  sql.NullString
}

type MovieOfTheDay struct {
	Date    time.Time
	MovieID int32
}
