// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie_of_the_day.sql

package database

import (
	"context"
	"time"
)

const getMovieOfTheDay = `-- name: GetMovieOfTheDay :one
SELECT movies.title, movies.tagline, movies.genres, movies.director, movies.actor1, movies.actor2, movies.year
FROM movie_of_the_day
INNER JOIN movies
ON movie_of_the_day.movie_id = movies.id
WHERE movie_of_the_day.date = $1
`

type GetMovieOfTheDayRow struct {
	Title    string
	Tagline  string
	Genres   string
	Director string
	Actor1   string
	Actor2   string
	Year     int32
}

func (q *Queries) GetMovieOfTheDay(ctx context.Context, date time.Time) (GetMovieOfTheDayRow, error) {
	row := q.db.QueryRowContext(ctx, getMovieOfTheDay, date)
	var i GetMovieOfTheDayRow
	err := row.Scan(
		&i.Title,
		&i.Tagline,
		&i.Genres,
		&i.Director,
		&i.Actor1,
		&i.Actor2,
		&i.Year,
	)
	return i, err
}
