// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movie_of_the_day.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const getMovieOfTheDay = `-- name: GetMovieOfTheDay :one
SELECT
    movies.id,
    movies.title,
    movies.tagline,
    movies.genres,
    movies.director,
    movies.actor1,
    movies.actor2,
    movies.year,
    movies.poster_path
FROM movie_of_the_day
INNER JOIN movies
ON movie_of_the_day.movie_id = movies.id
WHERE movie_of_the_day.date = $1
`

type GetMovieOfTheDayRow struct {
	ID         int32
	Title      string
	Tagline    sql.NullString
	Genres     pqtype.NullRawMessage
	Director   sql.NullString
	Actor1     sql.NullString
	Actor2     sql.NullString
	Year       sql.NullInt32
	PosterPath sql.NullString
}

func (q *Queries) GetMovieOfTheDay(ctx context.Context, date time.Time) (GetMovieOfTheDayRow, error) {
	row := q.db.QueryRowContext(ctx, getMovieOfTheDay, date)
	var i GetMovieOfTheDayRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Tagline,
		&i.Genres,
		&i.Director,
		&i.Actor1,
		&i.Actor2,
		&i.Year,
		&i.PosterPath,
	)
	return i, err
}

const getMovieOfTheDayDatesInRange = `-- name: GetMovieOfTheDayDatesInRange :many
SELECT date
FROM movie_of_the_day
WHERE date >= $1 AND date <= $2
`

type GetMovieOfTheDayDatesInRangeParams struct {
	Date   time.Time
	Date_2 time.Time
}

func (q *Queries) GetMovieOfTheDayDatesInRange(ctx context.Context, arg GetMovieOfTheDayDatesInRangeParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, getMovieOfTheDayDatesInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var date time.Time
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMovieOfTheDay = `-- name: InsertMovieOfTheDay :exec
INSERT INTO movie_of_the_day (date, movie_id)
VALUES ($1, $2)
ON CONFLICT (date) DO NOTHING
`

type InsertMovieOfTheDayParams struct {
	Date    time.Time
	MovieID int32
}

func (q *Queries) InsertMovieOfTheDay(ctx context.Context, arg InsertMovieOfTheDayParams) error {
	_, err := q.db.ExecContext(ctx, insertMovieOfTheDay, arg.Date, arg.MovieID)
	return err
}
