// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
)

const searchMovies = `-- name: SearchMovies :many
SELECT title, year
FROM movies
WHERE title ILIKE $1
LIMIT 20
`

type SearchMoviesRow struct {
	Title string
	Year  int32
}

func (q *Queries) SearchMovies(ctx context.Context, title string) ([]SearchMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMovies, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMoviesRow
	for rows.Next() {
		var i SearchMoviesRow
		if err := rows.Scan(&i.Title, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
