// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"database/sql"
)

const searchMovies = `-- name: SearchMovies :many
SELECT title, year
FROM movies
WHERE title ILIKE $1
LIMIT 20
`

type SearchMoviesRow struct {
	Title string
	Year  int32
}

func (q *Queries) SearchMovies(ctx context.Context, title string) ([]SearchMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMovies, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMoviesRow
	for rows.Next() {
		var i SearchMoviesRow
		if err := rows.Scan(&i.Title, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMoviePoster = `-- name: UpdateMoviePoster :exec
UPDATE movies
SET poster_url = $1
WHERE id = $2
`

type UpdateMoviePosterParams struct {
	PosterUrl sql.NullString
	ID        int32
}

func (q *Queries) UpdateMoviePoster(ctx context.Context, arg UpdateMoviePosterParams) error {
	_, err := q.db.ExecContext(ctx, updateMoviePoster, arg.PosterUrl, arg.ID)
	return err
}
