services:
  letterboxle-backend:
    container_name: letterboxle-backend
    build: .
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - PLATFORM=${PLATFORM}
      - PORT=${PORT}
      - TMDB_API_READ_ACCESS_TOKEN=${TMDB_API_READ_ACCESS_TOKEN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    networks:
      - npm

networks:
  npm:
    external: true