name: cd

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    env:
      DB_URL: ${{ secrets.DB_URL }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      PLATFORM: "prod"
      PORT: "8080"

    steps:
      - name: Install cloudflared
        env:
          CLOUDFLARED_VERSION: "2026.9.1"
          CLOUDFLARED_DEB_SHA256: "3be76adc4185d36a0bfb4c2dd8663292f0ed363797f2180333b513b43c81d419"
        run: |
          curl -L --output cloudflared.deb "https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-amd64.deb"
          echo "${CLOUDFLARED_DEB_SHA256}  cloudflared.deb" | sha256sum -c -
          sudo apt install ./cloudflared.deb

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          echo "Host $SSH_HOST" >> ~/.ssh/config
          echo "  ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" >> ~/.ssh/config
          echo "  StrictHostKeyChecking yes" >> ~/.ssh/config

      - name: Deploy via SSH
        run: |
          ssh "$SSH_USER@$SSH_HOST" "
            cd ~/Letterboxle-backend && \
            git pull origin main && \
            echo \"DB_URL=$DB_URL\" > .env && \
            echo \"TMDB_API_KEY=$TMDB_API_KEY\" >> .env && \
            echo \"PLATFORM=$PLATFORM\" >> .env && \
            echo \"PORT=$PORT\" >> .env && \
            docker compose up -d --build && \
            echo 'Running Migrations...' && \
            docker compose exec -T letterboxle-backend sh -c 'goose -dir sql/schema postgres \"\$DB_URL\" up'
          "